aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples

scripts/publish-instance-metrics/amazon-cloudwatch-agent.json
scripts/publish-instance-metrics/on-start.sh

**Description of changes:**  Notebook Instances do not publish any metrics to CloudWatch unlike other components like Endpoints. This prevents us from observing any metrics and in turn creating alarms on those metrics.
Thus, here we use the Unified CloudWatch Agent to publish the metrics to Cloudwatch
(If adding a Lifecycle Configuration, please provide *exact* commands or steps to run on a Notebook Instance to validate)
To test this, update the wget command as below:
wget https://raw.githubusercontent.com/imujjwal96/amazon-sagemaker-notebook-instance-lifecycle-config-samples/metrics/scripts/publish-instance-metrics/amazon-cloudwatch-agent.json
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

Add script for notebook instance metrics

---

README.md

- On BSDs the || should be wrapped in brackets or you get an error:
$ aws sagemaker create-notebook-instance-lifecycle-config     --notebook-instance-lifecycle-config-name "$RESOURCE_NAME"     --on-start Content=$(cat script/$SCRIPT_NAME/on-start.sh || echo ""| base64)
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:
aws help
aws <command> help
aws <command> <subcommand> help
Unknown options: -e, OVERVIEW, #, This, script, ... EOF, #
- On GNU based releases, like the notebook instance, this command should be:
aws sagemaker create-notebook-instance-lifecycle-config     --notebook-instance-lifecycle-config-name "$RESOURCE_NAME"     --on-start Content=$((cat …

Update README.md CreateLifecycleConfiguration command

---

scripts/auto-stop-idle/autostop.py
scripts/auto-stop-idle/on-start.sh

Autostop SageMaker notebook when idle

---

scripts/proxy-for-jupyter/on-start.sh

This script enable customer to setup proxy settings for the Jupyter notebooks and the SageMaker notebook instance. In order for the Jupyter notebooks to be able to pick up the proxy settings from the Lifecycle Configuration, we need to specify these settings in the ipython notebook server environment. To configure the ipython notebook server profile, we will create a simple python script 00-startup.py under /home/ec2-user/.ipython/profile_default/startup path (the 00 in the script name is because scripts under this path are run in lexicographical order, and we want this to be run first). 
Additionally, the default terminal shell that is spawned whenever you open a terminal in Jupyter is a non-logging shell, i.e., it is an interactive shell. Therefore, for the proxy settings to be apply to …

 Updated the script for proxy settings 

---

scripts/install-conda-package-all-environments/on-start.sh

#7 
Further improve the directions as ```sudo -b``` is necessary to truly ensure that the process runs in the background.  nohup, alone, doesn't background the process, you must either submit a job (via "&") or use sudo's built-in support for background processes.
- [N/A] Documentation in the script around any network access requirements
- [N/A] Documentation in the script around any IAM permission requirements
- [N/A] CLI commands used to validate functionality on the instance

Further improve instructions

---

scripts/set-env-variable/on-start.sh
scripts/set-git-config/on-start.sh

**Description**
Add script for setting env variable and configuring Git
**Motivation**
Add a way to set env varible in lifecycle config so it could be used in all Jupyter envs. Add a way to set Git config. For now user is default to ec2-user and email is default to host ip.
* Verified that env variable is set
* Verified that username and email are set in Git config
- [x ] Notebook Instance created successfully with the Lifecycle Configuration
- [x ] Notebook Instance stopped and started successfully
```
echo $YOUR_ENV_VARIABLE_NAME
git config --list
```

Add script for setting env variable and configuring Git

---

README.md
scripts/execute-notebook-on-startup/on-start.sh

- [N/A] Documentation in the script around any network access requirements
- [N/A] Documentation in the script around any IAM permission requirements
- [N/A] CLI commands used to validate functionality on the instance
```
Verified that I'm able to see the executed `MyNotebook.ipynb` on the instance.
```

Script to execute notebook file on startup using nbconvert

---

scripts/auto-stop-idle/autostop.py
scripts/auto-stop-idle/on-start.sh

16
This fixes the script behavior to auto-stop the instance if no one has connected to it. 
Essentially if there are no kernels on the notebook server, it checks the LastModifiedTime to determine the last Start/Stop time and checks that against idle timeout.
```
See scripts/auto-stop-idle/autostop.py for changes.
```

bug fix: Fix auto stop for session-less notebooks instances

---

scripts/set-env-variable/on-start.sh

Fix to set-env script to properly set "TAG" variable
```
```

Update on-start set-env script with bug fix for setting tag variable

---

scripts/install-conda-package-all-environments/on-start.sh
scripts/install-conda-package-single-environment/on-start.sh
scripts/install-lab-extension/on-start.sh
scripts/install-nb-extension/on-start.sh
scripts/install-pip-package-all-environments/on-start.sh
scripts/install-pip-package-single-environment/on-start.sh
scripts/install-server-extension/on-start.sh
scripts/persistent-conda-ebs/on-create.sh
scripts/persistent-conda-ebs/on-start.sh
scripts/set-git-config/on-start.sh

**Issue #, if available:** n/a
**Description of changes:** Any Notebook Instance I created with any of the scripts changed in this PR as their Lifecycle Configuration would time out and fail to start. This is because the delimiter `'EOF'` at the beginning of each `heredoc` had single quotes whereas the delimiter used at the end had none (i.e. `EOF`). This caused the match to fail and the scripts to never complete and return to the shell.
To test `set-git-config/on-start.sh`:
```bash
$ git config --global user.name
$ git config --global user.email
```

Enable scripts to complete properly

---

scripts/install-conda-package-single-environment/on-start.sh

Issue #28
Scripts returns a "ArgumentError: Argument --name requires a value." if run as a Start notebook script on AWS SageMaker. 
To resolve this, I added single quotes around EOF and the scripts runs successfully, installing the package specified.
```
#!/bin/bash
set -e
sudo -u ec2-user -i <<'EOF'
PACKAGE=tabulate
ENVIRONMENT=python3
conda install "$PACKAGE" --name "$ENVIRONMENT" --yes
EOF
[15:24:04] The following NEW packages will be INSTALLED: tabulate: 0.8.3-py36_0
[15:24:04] Downloading and Extracting Packages
[15:24:04] Preparing transaction: ...working... done
[15:24:04] Verifying transaction: ...working... done
[15:24:04] Executing transaction: ...working... done
sh-4.2$ conda list tabulate -n "python3"
# …
```

Added single quotes around EOF to resolve error

---

scripts/install-lab-extension/on-start.sh
scripts/install-nb-extension/on-start.sh

**Issue #, if available:** #32 
**Description of changes:** Escape $ in variable names within the `sudo -u ec2-user -i <<EOF` pattern; which are otherwise resolved by the outer shell before passing to the subshell.
```
jupyter labextension list
```

Fix extension install scripts variable escaping

---

README.md
scripts/add-pypi-repository/on-start.sh

Subject says it all. 
Provide your commands here
I set up a private repo on an ec2 node in my VPC and was able to install a custom package that
doesn't exist in the regular PyPi repo. 
Also confirmed that, if I set DISABLE_PYPI, it looks only at the private index. 
Tested with and without direct internet connection enabled.
```
sh-4.2$ pip install sagemaker_run_notebook
Looking in indexes: http://172.31.24.20:8080/
Collecting sagemaker_run_notebook
Downloading http://172.31.24.20:8080/packages/sagemaker_run_notebook-0.0.1.tar.gz (9.1 kB)
Requirement already satisfied: boto3>=1.10.44 in ./anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages (from sagemaker_run_notebook) (1.12.27)
Requirement already satisfied: …
```

Added a script to configure private pypi repositories

---

scripts/auto-stop-idle/on-start.sh

**Issue # , if available:** #40 
**Description of changes:** Fix _auto_stop_idle.sh_ crontab to run _autostop.py_ script every 5 minutes.

Fix crontab for autostop when idle

---

README.md
scripts/notebook-history-s3/notebook-history-s3.py
scripts/notebook-history-s3/on-start.sh

N/a
Adds a script which writes the sqlite db to S3. This DB can be used to see cell execution history as well as session history.
When testing, you will have to modify the on-start.sh to point to the correct location for the raw python script location, as that location won't become valid until the changes are merged to master. My testing steps are below and require no modification to run.
```
sudo su
export PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
cd /
mkdir /scripts
mkdir /scripts/notebook-history-s3
cd /scripts/notebook-history-s3
wget https://raw.githubusercontent.com/jmgray24/amazon-sagemaker-notebook-instance-lifecycle-config-samples/master/scripts/notebook-history-s3/on-start.sh
sh …
```

Added new script for persisting history to S3

---

README.md
scripts/set-codecommit-cross-account-access/on-start.sh

Adds a script that configures cross-account access to CodeCommit repositories in another account. It basically automates the steps 3 and 4 of the instructions [here](https://docs.aws.amazon.com/sagemaker/latest/dg/nbi-git-cross.html) that would need to be executed every time the notebook is started otherwise.
```shell
cat ~/.aws/config  # notice there's only the default profile
cat ~/.gitconfig # notice credential helper doesn't have --profile
git clone <my_https_clone_url_from_another_account>
wget https://raw.githubusercontent.com/tuliocasagrande/amazon-sagemaker-notebook-instance-lifecycle-config-samples/master/scripts/set-codecommit-cross-account-access/on-start.sh
vim on-start.sh # or nano on-start.sh
bash …
```

Add cross-account CodeCommit access

---

README.md
scripts/migrate-ebs-data-backup/on-start.sh
scripts/migrate-ebs-data-sync/on-create.sh

None. This is to accompany an upcoming feature.
This pair of scripts help create a backup of `/home/ec2-user/SageMaker/` from an existing instance and downloads it to a new instance. 
```
cat << "EOF" > /home/ec2-user/backup.sh
#!/bin/bash
NOTEBOOK_ARN=$(jq '.ResourceArn' /opt/ml/metadata/resource-metadata.json --raw-output)
NOTEBOOK_NAME=$(jq '.ResourceName' /opt/ml/metadata/resource-metadata.json --raw-output)
BACKUP_DESTINATION=ebs-backup-bucket
BUCKET=$(aws sagemaker list-tags --resource-arn $NOTEBOOK_ARN  | jq -r --arg BACKUP_DESTINATION "$BACKUP_DESTINATION" .'Tags[] | select(.Key == $BACKUP_DESTINATION).Value' --raw-output)
echo "Checking if s3://${BUCKET} exists..."
aws s3api wait bucket-exists --bucket …
```

Adding two new scripts to help migrate data from an existing instance to a new instance.

---

scripts/publish-instance-metrics/on-start.sh

This change is to fix issue where customers are not seeing logs after running this LCC. Previously with
AL1, there were two cloudwatch instances running where the old process had old logging configs and
was publishing logs, while the newer process had the metrics configs and was publishing metrics.
For AL2 instead of starting a second process, it is actually restarting the old process, which results
in that new process only having metrics configs and not having any logging configs. As a result no
logs are emitted. This change will append the new configs so the process can publish both the logs
and the metrics.
```
```
By submitting this pull request, I confirm that you can use, modify, copy, and …

Append metrics configurations to existing logging configurations

---

scripts/auto-stop-idle/autostop.py

(https://t.corp.amazon.com/V746619799/overview)
print statements added to catch idle state settings in auto-stop-idle LCC python script autostop.py. 
Note:
Failure replication unsuccessful. Notebook instance successfully auto stops after I ran a 10 second auto stop cron within the instance. Cloud watch log aligns with auto stop behavior and no idle deactivation is logged.
```
```

Auto stop print logging to catch idle state setting

---

scripts/set-env-variable/on-start.sh

https://sim.amazon.com/issues/MD-10193
sub-issue created for issue - https://sim.amazon.com/issues/MD-10308
We have two Amazon Linux and Jupyter Lab versions available for notebook instance creations.  This code change determines which command to execute for system restart based on the current AL/JL version.
Executed on personal notebook instances with AL/JL version combinations.
```
```

Added logic to determine system restart based on AL and JL versions.

---

scripts/mount-fsx-lustre-file-system/on-start.sh
scripts/set-env-variable/on-start.sh

https://sim.amazon.com/issues/MD-10193
sub-issue created for issue - https://sim.amazon.com/issues/MD-10311
We have two Amazon Linux and Jupyter Lab versions available for notebook instance creations. This code change determines which command to execute for lustre installation based on the current AL/JL version.
Deployed to personal notebook instances with various AL and JL version combinations.
```
```

Added logic to determine lustre install based on AL/JL version. Removed error squash.

---

scripts/persistent-conda-ebs/on-start.sh

https://issues.amazon.com/issues/MD-10312
Added logic for restart command after conda ebs creation to be determined by running platform. 
LCC tested on legacy AL1v1 and new AL2v2 notebooks. 
Loaded current LCC and observed failure error:  ``` /tmp/OnStart_2022-11-17-19-092nflww27: line 33: restart: command not found ``` on AL2 notebook. AL1 was successful.
After inserting fix both notebooks are successful.
```
/your/commands/here
```

logic for restart command to work on AL1 and AL2 platforms.

---

scripts/auto-stop-idle/on-start.sh

Python3 in bin and Jupyter system Python on start do not support boto3 import. Need to dictate appropriate version to use for LCC. 
```
LCC load error:
+ /usr/bin/python -c 'import boto3'
--
<br class="Apple-interchange-newline">
2023-02-22T17:57:43.678-06:00CopyNo boto3 found in Python or Python3. Exiting... | No boto3 found in Python or Python3. Exiting...
-- | --
Jupyter environment version testing:
sh-4.2$ ls | grep python
python
python2
python2.7
python2.7-config
python2-config
python3
python3.7
python3.7m
python3.8
python3.8-config
python3.8-x86_64-config
python-config
sh-4.2$ /usr/bin/python3 --version
Python 3.7.16
sh-4.2$ /usr/bin/python3
Python 3.7.16 (default, Dec 15 2022, 23:24:54)
[GCC 7.3.1 20180712 (Red Hat 7.3.1-15)] …
```

Using conda python for boto3 install.

---

scripts/mount-fsx-lustre-file-system/on-start.sh

N/A
Current method of determining platform version is weak and prone to failure if AL1 ami packages get updated. This method searches for the more static AL1 site (https://aws.amazon.com/amazon-linux-ami/) string to determine appropriate command.
```
evidence of fsx mount creation in jupyter terminal:
sh-4.2$ cd /fsx/
sh-4.2$ 
```

Updated determination tag for AL1 platform to use website.
